[package]
name = "mac"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# tectmogul_project ={ path = "../../components/project"}
bevy = { workspace = true }
rand = { workspace = true }
bevy-inspector-egui = { workspace = true }
bevy-debug-camera = { workspace = true }
bevy_flycam ={ workspace = true }
bevy_rapier3d ={ workspace = true }
bevy_mod_picking ={ workspace = true }
bevy_transform_gizmo ={ workspace = true }
bevy_hanabi ={ workspace = true }

[[example]]
name = "shader_animate_shader"
path = "examples/shader/animate_shader.rs"

[[example]]
name = "shader_random_shader"
path = "examples/shader/random_shader.rs"

[lib]
name = "mac"
crate-type = ["rlib"]

